import 'models/product.dart';

const products = <Product>[
  Product(
    id: 'p1',
    name: 'Union Hoodie',
    description: 'Cozy hoodie with Union logo.',
    image: 'assets/images/hoodie.jpg',
    price: 39.99,
    collection: 'Clothing',
  ),
  Product(
    id: 'p2',
    name: 'Union Mug',
    description: 'Ceramic mug with branding.',
    image: 'assets/images/mug.jpg',
    price: 9.99,
    collection: 'Accessories',
  ),
  Product(
    id: 'p3',
    name: 'Union T-shirt',
    description: 'Classic t-shirt with Union logo.',
    image: 'assets/images/T_shirt.jpg',
    price: 19.99,
    collection: 'Clothing',
  ),
  Product(
    id: 'p4',
    name: 'Union Hat',
    description: 'Stylish hat with Union logo.',
    image: 'assets/images/hat.jpg',
    price: 14.99,
    collection: 'Accessories',
  ),
  // Beanies
  Product(
    id: 'p5',
    name: 'Black Beanie',
    description: 'A black beanie.',
    image: 'assets/images/Beanie-Black.webp',
    price: 12.99,
    collection: 'Beanies',
  ),
  Product(
    id: 'p6',
    name: 'Green Beanie',
    description: 'A green beanie.',
    image: 'assets/images/Beanie-Green.webp',
    price: 12.99,
    collection: 'Beanies',
  ),
  Product(
    id: 'p7',
    name: 'Purple Beanie',
    description: 'A purple beanie.',
    image: 'assets/images/Beanie-Purple.webp',
    price: 12.99,
    collection: 'Beanies',
  ),
  Product(
    id: 'p8',
    name: 'White Beanie',
    description: 'A white beanie.',
    image: 'assets/images/Beanie-White.jpg',
    price: 12.99,
    collection: 'Beanies',
  ),
  // Caps
  Product(
    id: 'p9',
    name: 'Black Cap',
    description: 'A black cap.',
    image: 'assets/images/Cap-Black.avif',
    price: 15.99,
    collection: 'Caps',
  ),
  Product(
    id: 'p10',
    name: 'Green Cap',
    description: 'A green cap.',
    image: 'assets/images/Cap-Green.webp',
    price: 15.99,
    collection: 'Caps',
  ),
  Product(
    id: 'p11',
    name: 'Grey Cap',
    description: 'A grey cap.',
    image: 'assets/images/Cap-Grey.webp',
    price: 15.99,
    collection: 'Caps',
  ),
  Product(
    id: 'p12',
    name: 'Navy Cap',
    description: 'A navy cap.',
    image: 'assets/images/Cap-Navy.webp',
    price: 15.99,
    collection: 'Caps',
  ),
  Product(
    id: 'p13',
    name: 'Purple Cap',
    description: 'A purple cap.',
    image: 'assets/images/Cap-Purple.avif',
    price: 15.99,
    collection: 'Caps',
  ),
  // Sweatshirts
  Product(
    id: 'p14',
    name: 'Biscuit Sweatshirt',
    description: 'A biscuit sweatshirt.',
    image: 'assets/images/BiscuitSweatshirt.webp',
    price: 29.99,
    collection: 'Sweatshirts',
  ),
  Product(
    id: 'p15',
    name: 'Caramel Sweatshirt',
    description: 'A caramel sweatshirt.',
    image: 'assets/images/CaramelSweatshirt.webp',
    price: 29.99,
    collection: 'Sweatshirts',
  ),
  Product(
    id: 'p16',
    name: 'Vanilla Sweatshirt',
    description: 'A vanilla sweatshirt.',
    image: 'assets/images/VanillaSweatshirt.webp',
    price: 29.99,
    collection: 'Sweatshirts',
  ),
  // Graduation
  Product(
    id: 'p17',
    name: 'Grey Graduation Hoodie',
    description: 'A grey graduation hoodie.',
    image: 'assets/images/GradGrey.avif',
    price: 45.99,
    collection: 'Graduation',
  ),
  Product(
    id: 'p18',
    name: 'Purple Graduation Hoodie',
    description: 'A purple graduation hoodie.',
    image: 'assets/images/GradPurple.webp',
    price: 45.99,
    collection: 'Graduation',
  ),
];
